// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlzvbzjwxkwqwtjqskso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1senZiemp3eGt3cXd0anFza3NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxODE0OTEsImV4cCI6MjA1NDc1NzQ5MX0.U6tLFT85m_twO96LeRSp9u58ml6nX6zfXOBFy_Eg3rg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);